/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLinkDialog: typeof import('./src/components/editor/bubble-menu/AddLinkDialog.vue')['default']
    BubbleMenu: typeof import('./src/components/editor/bubble-menu/BubbleMenu.vue')['default']
    ChildrenOptions: typeof import('./src/components/editor/note-children/ChildrenOptions.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    EditorOptions: typeof import('./src/components/editor/EditorOptions.vue')['default']
    EditorView: typeof import('./src/components/editor/EditorView.vue')['default']
    ElementDropdown: typeof import('./src/components/editor/bubble-menu/ElementDropdown.vue')['default']
    GenericButton: typeof import('./src/components/generic/GenericButton.vue')['default']
    GenericDialog: typeof import('./src/components/generic/GenericDialog.vue')['default']
    GenericErrorMessage: typeof import('./src/components/generic/GenericErrorMessage.vue')['default']
    LoadingOverlay: typeof import('./src/components/loading/LoadingOverlay.vue')['default']
    NewWorkspaceCard: typeof import('./src/components/workspace/NewWorkspaceCard.vue')['default']
    NoteChildren: typeof import('./src/components/editor/note-children/NoteChildren.vue')['default']
    NoteChildrenBig: typeof import('./src/components/editor/note-children/NoteChildrenBig.vue')['default']
    NoteChildrenSmall: typeof import('./src/components/editor/note-children/NoteChildrenSmall.vue')['default']
    RemoveDialog: typeof import('./src/components/workspace/dialog/RemoveDialog.vue')['default']
    RenameDialog: typeof import('./src/components/workspace/dialog/RenameDialog.vue')['default']
    RenameErrorMessage: typeof import('./src/components/editor/error/RenameErrorMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarButtons: typeof import('./src/components/sidebar/SidebarButtons.vue')['default']
    Spinner: typeof import('./src/components/loading/Spinner.vue')['default']
    WorkspaceCard: typeof import('./src/components/workspace/WorkspaceCard.vue')['default']
    WorkspaceMenuItem: typeof import('./src/components/workspace/WorkspaceMenuItem.vue')['default']
  }
}
