/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLinkDialog: typeof import('./src/components/editor/AddLinkDialog.vue')['default']
    BubbleMenu: typeof import('./src/components/editor/BubbleMenu.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    ElementDropdown: typeof import('./src/components/editor/ElementDropdown.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/sidebar/SidebarItem.vue')['default']
  }
}
