/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLinkDialog: typeof import('./src/components/editor/AddLinkDialog.vue')['default']
    BubbleMenu: typeof import('./src/components/editor/BubbleMenu.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    EditorOptions: typeof import('./src/components/editor/EditorOptions.vue')['default']
    EditorView: typeof import('./src/components/editor/EditorView.vue')['default']
    ElementDropdown: typeof import('./src/components/editor/ElementDropdown.vue')['default']
    GenericButton: typeof import('./src/components/GenericButton.vue')['default']
    GenericDialog: typeof import('./src/components/GenericDialog.vue')['default']
    GenericErrorMessage: typeof import('./src/components/GenericErrorMessage.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    NewWorkspaceCard: typeof import('./src/components/workspace/NewWorkspaceCard.vue')['default']
    RemoveDialog: typeof import('./src/components/workspace/dialog/RemoveDialog.vue')['default']
    RenameDialog: typeof import('./src/components/workspace/dialog/RenameDialog.vue')['default']
    RenameErrorMessage: typeof import('./src/components/RenameErrorMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarButtons: typeof import('./src/components/sidebar/SidebarButtons.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    WorkspaceCard: typeof import('./src/components/workspace/WorkspaceCard.vue')['default']
    WorkspaceMenuItem: typeof import('./src/components/workspace/WorkspaceMenuItem.vue')['default']
  }
}
